import './globals.css';
// Styles from UI library
import 'ui/styles.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en" className="bg-slate-900">
            <body className="text-white antialiased">{children}</body>
        </html>
    );
}
