import './globals.css';
// Styles from UI library
import 'ui/styles.css';

import localFont from '@next/font/local';

import {Header} from '../components/Header';
import {Sidebar} from '../components/Sidebar';

const inter = localFont({
    src: '../public/fonts/inter-var-latin.woff2',
    variable: '--font-inter',
    display: 'swap'
});

export const metadata = {
    title: {
        default: 'Tier Docs',
        template: '%s | Tier Docs'
    },
    description: 'Generated by create next app'
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en" className={`bg-slate-900 ${inter.variable}`}>
            <body className="text-white antialiased">
                <header className="fixed inset-0 z-40 flex">
                    <div className="block w-72 overflow-y-auto border-r border-white/10 px-6 pt-4 pb-8 ">
                        <div className="flex">
                            <p className="h-6">Logo</p>
                        </div>
                        <Header />
                        <Sidebar />
                    </div>
                </header>
                <div className="relative ml-72 px-8 pt-14">
                    <main className="py-16">{children}</main>
                </div>
            </body>
        </html>
    );
}
